baseURL = "https://blog.jonathanchannon.com/"
title = "Blog"
theme = "hugo-theme-massively"
googleAnalytics = "UA-7138405-4"
disqusShortname = "jonathanchannonblog"
disableKinds = ["taxonomy", "section"]
pagination.pageSize = 6

[Params]
    dateFormat = "Mon, Jan 2, 2006"

[Params.Posts]
    featuredpost = "true"
    showFirstLast = true

[Author]
    name = "Jonathan Channon Blog"

 [outputs]
    home = [ "HTML", "RSS" ]
    page = [ "HTML", "RSS" ]

 [outputFormats]
 [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[frontmatter]
date  = [":filename", ":default"]
publishDate = [":filename", ":default"]

[languages]
[languages.en]
  languageName = "English"

[Permalinks]
    post = "/:filename/"
    page = "/:filename/"